name: language_learning
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  #http requests
  dio: ^5.7.0

  #error handling
  dartz: ^0.10.1

  #toast message
  toastification: ^2.3.0

  #lottie:
  lottie: ^3.3.1

  #screen sizing
  flutter_screenutil: ^5.9.3

  #svg
  flutter_svg: ^2.0.16

  #otp view
  pinput: ^5.0.0

  #keyboard visibility detector
  flutter_keyboard_visibility: ^6.0.0

  #localization:
  easy_localization: ^3.0.7

  # state management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6

  retry: ^3.1.2
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.4
  rxdart: ^0.28.0
  http: ^1.3.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  flutter_tts: ^4.2.2

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/lotties/
      - assets/images/onboarding_hero.svg
      - assets/images/
      - assets/images/background.png
      - assets/images/flags/
      - assets/images/features/
      - assets/translation/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
          weight: 400

    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400
